version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: unicorn_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - priming-network

volumes:
  postgres_data:

networks:
  priming-network:
    name: priming-network
    driver: bridge
