config:
  phases:
    - duration: 60
      arrivalRate: 200
      name: Load testing the Priming API for 60 seconds with 200 concurrent requests/s
scenarios:
  - flow:
      - get:
          url: "{{ url }}"
